# Generated by Django 5.0.4 on 2024-06-16 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='Место привычки')),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 6, 16, 20, 58, 31, 989977), verbose_name='Время привычки')),
                ('action', models.CharField(max_length=150, verbose_name='Действие привычки')),
                ('sign_pleasant_habit', models.BooleanField(default=True, verbose_name='Признак приятной привычки')),
                ('frequency', models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Раз в день', max_length=50, verbose_name='Периодичность рассылки')),
                ('reward', models.CharField(max_length=150, verbose_name='Вознаграждение')),
                ('time_to_complete', models.DateTimeField(default=datetime.datetime(2024, 6, 16, 20, 58, 31, 989977), verbose_name='Время на выполнение')),
                ('publication_sign', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PleasantHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='Место привычки')),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 6, 16, 20, 58, 31, 989977), verbose_name='Время привычки')),
                ('action', models.CharField(max_length=150, verbose_name='Действие привычки')),
                ('time_to_complete', models.DateTimeField(default=datetime.datetime(2024, 6, 16, 20, 58, 31, 989977), verbose_name='Время на выполнение')),
                ('publication_sign', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Приятная привычка',
                'verbose_name_plural': 'Приятные привычки',
                'ordering': ('id',),
            },
        ),
    ]
