# Generated by Django 5.0.4 on 2024-06-20 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='frequency',
            field=models.CharField(choices=[('Раз в день', 'Раз в день'), ('По выходным', 'По выходным'), ('Раз в неделю', 'Раз в неделю')], default='Раз в день', max_length=50, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 21, 24, 56, 770125), verbose_name='Время привычки'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='time_to_complete',
            field=models.TimeField(default=2, verbose_name='Время на выполнение'),
        ),
        migrations.AlterField(
            model_name='pleasanthabit',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 21, 24, 56, 769126), verbose_name='Время привычки'),
        ),
        migrations.AlterField(
            model_name='pleasanthabit',
            name='time_to_complete',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 21, 24, 56, 769126), verbose_name='Время на выполнение'),
        ),
    ]
