# Generated by Django 5.0.4 on 2024-06-22 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habits_frequency_alter_habits_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='frequency',
            field=models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю')], default='Раз в день', max_length=50, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='publication_sign',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='sign_pleasant_habit',
            field=models.BooleanField(default=False, verbose_name='Признак приятной привычки'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 22, 21, 38, 22, 171706), null=True, verbose_name='Время привычки'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='time_to_complete',
            field=models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Время на выполнение'),
        ),
        migrations.AlterField(
            model_name='pleasanthabit',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 21, 38, 22, 170707), verbose_name='Время привычки'),
        ),
        migrations.AlterField(
            model_name='pleasanthabit',
            name='time_to_complete',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 21, 38, 22, 170707), verbose_name='Время на выполнение'),
        ),
    ]
