# Generated by Django 5.0.4 on 2024-06-22 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habits_frequency_alter_habits_publication_sign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 22, 21, 38, 33, 176101), null=True, verbose_name='Время привычки'),
        ),
        migrations.AlterField(
            model_name='pleasanthabit',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 21, 38, 33, 175101), verbose_name='Время привычки'),
        ),
        migrations.AlterField(
            model_name='pleasanthabit',
            name='time_to_complete',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 21, 38, 33, 175101), verbose_name='Время на выполнение'),
        ),
    ]
